import Enums from 'utils/EnumsManager';

const { ReduxActionTypePrefix } = Enums;
const { OBJECTDETAILS } = ReduxActionTypePrefix;

export const SET_SECTIONS = `${OBJECTDETAILS}_SET_SECTIONS`;
export const SET_ACTIVE_FIELD = `${OBJECTDETAILS}_SET_ACTIVE_FIELD`;
export const RESET_ACTIVE_FIELD = `${OBJECTDETAILS}_RESET_ACTIVE_FIELD`;
export const SET_FIELD_VALUE = `${OBJECTDETAILS}_SET_FIELD_VALUE`;
export const RESET_FIELD_VALUE = `${OBJECTDETAILS}_RESET_FIELD_VALUE`;
export const RESET_ALL_FIELDS = `${OBJECTDETAILS}_RESET_ALL_FIELDS`;
export const SET_NEW_ID = `${OBJECTDETAILS}_SET_NEW_ID`;
export const RESET_ID = `${OBJECTDETAILS}_RESET_ID`;
export const RESET = `${OBJECTDETAILS}_RESET`;

// un
// export const SET_FIELD_OPTIONS = VIEWDETAILS + 'SET_FIELD_OPTIONS';
