export const NEW_TEMPLATE_FOLDER = 'NEW_TEMPLATE_FOLDER';
export const NEW_TEMPLATE_NAME = 'NEW_TEMPLATE_NAME';
export const NEW_TEMPLATE_API_NAME = 'NEW_TEMPLATE_API_NAME';
export const NEW_TEMPLATE_DESCRIPTION = 'NEW_TEMPLATE_DESCRIPTION';
export const NEW_TEMPLATE_CONTENT = 'NEW_TEMPLATE_CONTENT';