import { combineReducers } from 'redux';
import { FETCH_SUCCESS, DELETE_SUCCESS } from './actionTypes';
import Enums from 'utils/EnumsManager';
// test
const example = [
  {
    "id": 1,
    "model_type": "App\\Model\\Lead",
    "field_name": "created_by_user_id_id",
    "crm_data_type": "number",
    "field_label": "created_by_user_id_name",
    "notnull": 0,
    "helper_text": null,
    "description": "seeder generated",
    "can_be_mapped": 1,
    "configurable": 0,
    "is_merge_master": 1,
    "precision": 10,
    "scale": 0,
    "length": null
  },      
  {
    "id": 3,
    "model_type": "App\\Model\\Lead",
    "field_name": "name",
    "crm_data_type": "text",
    "field_label": "name",
    "notnull": 1,
    "helper_text": null,
    "description": "seeder generated",
    "can_be_mapped": 1,
    "configurable": 1,
    "is_merge_master": 0,
    "precision": 10,
    "scale": 0,
    "length": 191
  },
  {
    "id": 18,
    "model_type": "App\\Model\\Lead",
    "field_name": "date_of_incorporation",
    "crm_data_type": "date",
    "field_label": "date_of_incorporation",
    "notnull": 0,
    "helper_text": null,
    "description": "seeder generated",
    "can_be_mapped": 1,
    "configurable": 1,
    "is_merge_master": 0,
    "precision": 10,
    "scale": 0,
    "length": null
  },
  {
    "id": 23,
    "model_type": "App\\Model\\LeadCstm",
    "field_name": "c__a1",
    "crm_data_type": "picklist",
    "field_label": "c__a1",
    "notnull": 0,
    "helper_text": null,
    "description": "seeder generated",
    "can_be_mapped": 1,
    "configurable": 1,
    "is_merge_master": 0,
    "precision": 10,
    "scale": 0,
    "length": 191,
    "picklist": {
      "data": [
        {
          "id": 2,
          "option_value": "AU",
          "option_tip": null,
          "display_num": 2
        },
        {
          "id": 1,
          "option_value": "CN",
          "option_tip": null,
          "display_num": 3
        }
      ]
    }
  },
  {
    "id": 24,
    "model_type": "App\\Model\\LeadCstm",
    "field_name": "c__a2",
    "crm_data_type": "text",
    "field_label": "c__a2",
    "notnull": 0,
    "helper_text": null,
    "description": "seeder generated",
    "can_be_mapped": 1,
    "configurable": 1,
    "is_merge_master": 0,
    "precision": 10,
    "scale": 0,
    "length": 191
  },
  {
    "id": 26,
    "model_type": "App\\Model\\LeadCstm",
    "field_name": "c__a4",
    "crm_data_type": "datetime",
    "field_label": "c__a4",
    "notnull": 0,
    "helper_text": null,
    "description": "seeder generated",
    "can_be_mapped": 1,
    "configurable": 1,
    "is_merge_master": 0,
    "precision": 10,
    "scale": 0,
    "length": null
  }
];
const sample = [
  {
      "id": 1,
      "created_by_user_id": null,
      "ownership_id": 1,
      "name": "test0",
      "first_name": "test0",
      "last_name": "test0",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "0@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "CN",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:30",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-2",
      "c__a2": "customer.c__a1-11",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 2,
      "created_by_user_id": 1,
      "ownership_id": null,
      "name": "test1",
      "first_name": "test1",
      "last_name": "test1",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "1@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "CN",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-3",
      "c__a2": "customer.c__a1-33",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 3,
      "created_by_user_id": null,
      "ownership_id": 0,
      "name": "test2",
      "first_name": "test2",
      "last_name": "test2",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "2@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "CN",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-2",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 4,
      "created_by_user_id": 0,
      "ownership_id": 2,
      "name": "test3",
      "first_name": "test3",
      "last_name": "test3",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "3@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "US",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-2",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 5,
      "created_by_user_id": 2,
      "ownership_id": null,
      "name": "test4",
      "first_name": "test4",
      "last_name": "test4",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "4@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "AU",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-2",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 6,
      "created_by_user_id": null,
      "ownership_id": 1,
      "name": "test5",
      "first_name": "test5",
      "last_name": "test5",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "5@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "US",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-1",
      "c__a2": "customer.c__a1-33",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 7,
      "created_by_user_id": 0,
      "ownership_id": 2,
      "name": "test6",
      "first_name": "test6",
      "last_name": "test6",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "6@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "US",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-1",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 8,
      "created_by_user_id": 2,
      "ownership_id": 0,
      "name": "test7",
      "first_name": "test7",
      "last_name": "test7",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "7@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "US",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-3",
      "c__a2": "customer.c__a1-33",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 9,
      "created_by_user_id": null,
      "ownership_id": null,
      "name": "test8",
      "first_name": "test8",
      "last_name": "test8",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "8@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "AU",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-1",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 10,
      "created_by_user_id": 2,
      "ownership_id": 1,
      "name": "test9",
      "first_name": "test9",
      "last_name": "test9",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "9@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "CN",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-1",
      "c__a2": "customer.c__a1-11",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 11,
      "created_by_user_id": 2,
      "ownership_id": 2,
      "name": "test10",
      "first_name": "test10",
      "last_name": "test10",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "10@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "CN",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-2",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 12,
      "created_by_user_id": 1,
      "ownership_id": 1,
      "name": "test11",
      "first_name": "test11",
      "last_name": "test11",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "11@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "US",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-3",
      "c__a2": "customer.c__a1-33",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 13,
      "created_by_user_id": null,
      "ownership_id": 1,
      "name": "test12",
      "first_name": "test12",
      "last_name": "test12",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "12@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "AU",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-1",
      "c__a2": "customer.c__a1-22",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 17,
      "created_by_user_id": null,
      "ownership_id": 1,
      "name": "test16",
      "first_name": "test16",
      "last_name": "test16",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "16@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "AU",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-2",
      "c__a2": "customer.c__a1-11",
      "c__a3": null,
      "c__a4": null
  },
  {
      "id": 19,
      "created_by_user_id": null,
      "ownership_id": 2,
      "name": "test18",
      "first_name": "test18",
      "last_name": "test18",
      "lead_type": "Demo",
      "lead_status": "Open",
      "phone": "1234567",
      "email": "18@acy.com",
      "address": null,
      "state": "chengdu",
      "country_code": "CN",
      "company_name": null,
      "company_type": null,
      "company_phone": null,
      "company_address": null,
      "business_registration_number": null,
      "date_of_incorporation": null,
      "description": null,
      "created_at": "2018-03-02 05:41:31",
      "updated_at": "2018-03-02 05:41:31",
      "c__a1": "customer.c__a1-3",
      "c__a2": "customer.c__a1-11",
      "c__a3": null,
      "c__a4": null
  }
];
// test ends
const initialState = {
  columns: example,
  data: sample,
  pagination: {},
};


const table = (state = initialState, action) => {
  switch (action.type) {
    case FETCH_SUCCESS:
      const { index, selector_meta } = action.payload;
      const { data, meta } = index;
      const { pagination } = meta;
      const columns = selector_meta.data;
      return {
        columns,
        data,
        pagination,
      };
    case DELETE_SUCCESS:
      const { id } = action.payload;
      const dataCopy = state.data;
      const deletedData = dataCopy.filter(record => record.id != id);
      return {
        ...state,
        data: deletedData,
      };
    default:
      return state;
  }
};

export default table;