// add new team
export const ORGCHART_SET_NEW_DEPARTMENT_NAME = 'ORGCHART_SET_NEW_DEPARTMENT_NAME';
export const ORGCHART_RESET_NEW_DEPARMENT = 'ORGCHART_RESET_NEW_DEPARMENT';

// tree
export const ORGCHART_SET_SELECTED_DEPARTMENT = 'ORGCHART_SET_SELECTED_DEPARTMENT';

// user
export const ORGCHART_SET_USER = 'ORGCHART_SET_USER';
export const ORGCHART_SET_SELECT_USER = 'ORGCHART_SET_SELECT_USER';

// sort team tree
export const ORGCHART_SET_SORTING_TEAM = 'ORGCHART_SET_SORTING_TEAM';

// ui
export const ORGCHART_SET_ADD_VISIBLE = 'ORGCHART_SET_ADD_VISIBLE';
export const ORGCHART_SET_SORTABLE_VIEW_VISIBLE = 'ORGCHART_SET_SORTABLE_VIEW_VISIBLE';
export const ORGCHART_SET_SELECTED_USER_TEAM_DIALOG_VISIBLE = 'ORGCHART_SET_SELECTED_USER_TEAM_DIALOG_VISIBLE';


