// add new team
export const EMAIL_TEMPLATES_SET_NEW_DEPARTMENT_NAME = 'EMAIL_TEMPLATES_SET_NEW_DEPARTMENT_NAME';
export const EMAIL_TEMPLATES_RESET_NEW_DEPARMENT = 'EMAIL_TEMPLATES_RESET_NEW_DEPARMENT';

// tree
export const EMAIL_TEMPLATES_SET_SELECTED_DEPARTMENT = 'EMAIL_TEMPLATES_SET_SELECTED_DEPARTMENT';

// user
export const EMAIL_TEMPLATES_SET_USER = 'EMAIL_TEMPLATES_SET_USER';
export const EMAIL_TEMPLATES_SET_SELECT_USER = 'EMAIL_TEMPLATES_SET_SELECT_USER';

// sort team tree
export const EMAIL_TEMPLATES_SET_SORTING_TEAM = 'EMAIL_TEMPLATES_SET_SORTING_TEAM';

// ui
export const EMAIL_TEMPLATES_SET_ADD_VISIBLE = 'EMAIL_TEMPLATES_SET_ADD_VISIBLE';
export const EMAIL_TEMPLATES_EDIT_FOLDER_VIEW_VISIBLE = 'EMAIL_TEMPLATES_EDIT_FOLDER_VIEW_VISIBLE';
export const EMAIL_TEMPLATES_SET_SELECTED_USER_TEAM_DIALOG_VISIBLE = 'EMAIL_TEMPLATES_SET_SELECTED_USER_TEAM_DIALOG_VISIBLE';


