export const SET_EDIT_USER = 'SET_EDIT_USER';
export const SAVE_USER = 'SAVE_USER';
export const SET_PAGENATIONS = 'SET_PAGENATIONS';
export const SET_USERS = 'SET_USERS';

export const TOGGLE_DEPARTMENT_SELECT_DIALOG = 'TOGGLE_DEPARTMENT_SELECT_DIALOG';
export const SET_DEPARTMENT = 'SET_DEPARTMENT';
