export default {
  zh: {
    tooltip: {
      field: '可选的字段不包括由系统自动生成值的字段。比如：created by字段。',
    },
  },
  en: {
    tooltip: {
      field: 'Fields whose value are generated by system automatically are not available for updating. e.g. "created by" field',
    },
  },
};
