//templates
export const EMAIL_TEMPLATES_SET_TEMPLATES = 'EMAIL_TEMPLATES_SET_TEMPLATES';
export const EMAIL_TEMPLATES_SETUP_TEMPLATES_PAGENATIONS = 'EMAIL_TEMPLATES_SETUP_TEMPLATES_PAGENATIONS;';
export const EMAIL_TEMPLATES_UPDATE_TEMPLATE = 'EMAIL_TEMPLATES_UPDATE_TEMPLATE';