export const ItemTypes = {
  FIELD: 'FIELD',
  SECTION: 'SECTION',
  MODULE: 'MODULE',
  TOOL: 'TOOL',
  MODULE_FIELD: 'MODULE_FIELD',
  TOOL_FIELD: 'TOOL_FIELD',
  SECTION_FIELD: 'SECTION_FIELD',
};
