
export const SETUP_FIELDS_SET_CURRENT_OBJECT = 'SETUP_FIELDS_SET_CURRENT_OBJECT';
export const SETUP_FIELDS_SET_OTHER_OBJECT_FILEDS = 'SETUP_FIELDS_SET_OTHER_OBJECT_FILEDS';
export const SETUP_FIELDS_SELECT_FIELD = 'SETUP_FIELDS_SELECT_FIELD';
export const SETUP_FIELDS_CHANGE_MAPPING_FIELD_STATUS = 'SETUP_FIELDS_CHANGE_MAPPING_FIELD_STATUS';

export const SETUP_FIELDS_TOGGLE_EDITING = 'SETUP_FIELDS_TOGGLE_EDITING';
