export const SETUP_FIELDS_SET_CURRENT_OBJECT = 'SETUP_FIELDS_SET_CURRENT_OBJECT';

/* table view action */
export const SETUP_FIELDS_SET_OTHER_OBJECT_FILEDS = 'SETUP_FIELDS_SET_OTHER_OBJECT_FILEDS';
export const SETUP_FIELDS_SELECT_FIELD = 'SETUP_FIELDS_SELECT_FIELD';
export const SETUP_FIELDS_CHANGE_MAPPING_FIELD_STATUS = 'SETUP_FIELDS_CHANGE_MAPPING_FIELD_STATUS';

export const SETUP_FIELDS_TOGGLE_EDITING = 'SETUP_FIELDS_TOGGLE_EDITING';

/* add field */
export const SETUP_FIELDS_SET_ADDED_ATTR = 'SETUP_FIELDS_SET_ADDED_ATTR';
export const SETUP_FIELDS_RESET_ADDED_ATTR = 'SETUP_FIELDS_RESET_ADDED_ATTR';
export const SETUP_FIELDS_SET_OBJECT_LAYOUT = 'SETUP_FIELDS_SET_OBJECT_LAYOUT';
