
export const TASK_LIST_PAGENATIONS = 'TASK_LIST_PAGENATIONS';
export const TASK_LIST_DATA = 'TASK_LIST_DATA';
export const TASK_LIST_PERIOD = 'TASK_LIST_PERIOD';
export const TASK_STATUS = 'TASK_STATUS';

