export const NEW_EMAIL_UPDATE_SELECTED_TEMPLATE = "NEW_EMAIL_UPDATE_SELECTED_TEMPLATE";
export const NEW_EMAIL_SET_TEMPLATES = "NEW_EMAIL_SET_TEMPLATES";
export const NEW_EMAIL_TEMPLATES_PAGENATIONS = "NEW_EMAIL_TEMPLATES_PAGENATIONS";