export const ADD_FIELD_TO_SECTION = 'ADD_FIELD_TO_SECTION';
export const DELETE_FROM_SECTION = 'DELETE_FROM_SECTION';
export const MOVE_BETWEEN_SECTION = 'MOVE_BETWEEN_SECTION';
export const ADD_SECTION = 'ADD_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';
export const UPDATE_SECTION = 'UPDATE_SECTION';
export const MOVE_SECTION = 'MOVE_SECTION';

export const TOGGLE_SECTION_ADD_EDIT_DIALOG = 'TOGGLE_SECTION_ADD_EDIT_DIALOG';
export const SET_SECTION_LABEL = 'SET_SECTION_LABEL';