export const SETUP_USERS_EDIT_USER = 'SETUP_USERS_EDIT_USER';
export const SETUP_USERS_SAVE_USER = 'SETUP_USERS_SAVE_USER';
export const SETUP_USERS_PAGENATIONS = 'SETUP_USERS_PAGENATIONS';
export const SETUP_USERS_SEARCHKEY = 'SETUP_USERS_SEARCHKEY';
export const SETUP_USERS_USERS = 'SETUP_USERS_USERS';

export const SETUP_USERS_TOGGLE_DEPARTMENT_SELECT_DIALOG = 'SETUP_USERS_TOGGLE_DEPARTMENT_SELECT_DIALOG';
export const SETUP_USERS_DEPARTMENT = 'SETUP_USERS_DEPARTMENT';
