export const SET_TASK_ASSIGNEE = 'SET_TASK_ASSIGNEE';
export const SET_TASK_ASSIGNEES = 'SET_TASK_ASSIGNEES';
export const SET_TASK_FIELD = 'SET_TASK_FIELD';
export const SET_TASK_FIELDS = 'SET_TASK_FIELDS';
export const ADD_NEW_SUBJECT = 'ADD_NEW_SUBJECT';
export const SET_TASK_SUBJECTS = 'SET_TASK_SUBJECTS';
export const REMOVE_MY_SUBJECT = 'REMOVE_MY_SUBJECT';
